name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t j22868706/my_first_react_app .
      - name: Publish image to Docker Hub
        run: docker push j22868706/my_first_react_app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Pull image from Docker Hub
        run: docker pull j22868706/my_first_react_app:latest
      - name: Check if container exists and remove it
        run: |
          if docker ps -a --format '{{.Names}}' | grep -Eq "^reactContainer$"; then
            docker rm -f reactContainer
          fi
      - name: Run Docker container
        run: docker run -d -p 3000:80 --name reactContainer j22868706/my_first_react_app:latest
