name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t j22868706/my_first_react_app .
      - name: Publish image to Docker Hub
        run: docker push j22868706/my_first_react_app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull j22868706/my_first_react_app:latest
            sudo docker kill test1
            sudo docker rm test1
            sudo docker run -d -p 80:80 --name test1 j22868706/my_first_react_app:latest
